- name: Ensure kube config directory exists (on master only)
  file:
    path: /home/ansadmin/.kube
    state: directory
    mode: '0700'
  become: yes
  become_user: ansadmin
  when: inventory_hostname == "localhost"

- name: Copy admin.conf to .kube/config (on master only)
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansadmin/.kube/config
    mode: '0600'
  become: yes
  become_user: ansadmin
  when: inventory_hostname == "localhost"

- name: Deploy app using kubectl (on master only)
  shell: kubectl apply -f /var/lib/jenkins/workspace/Finance-Project_dev/deployment.yaml
  become: yes
  become_user: ansadmin
  when: inventory_hostname == "localhost"
